# 🧹 Part 1 · Data Cleaning
### Accenture Project Cycle Datathon - Customer Churn & Retention

**Garbage in, garbage out.** A model is only as good as the data it learns from, so before any modelling this notebook makes the raw `users.csv` *trustworthy*. Cleaning has three jobs:

1. **Remove duplicates** that would skew the data
2. **Fix inconsistent formatting** so categories aren't fragmented
3. **Handle missing values** by dropping or imputing them

We finish by splitting into train/test sets and saving the cleaned data for the next notebook.

> 📘 For the full walkthrough, see the [Info Pack](../INFO_PACK.md#part-1--data-cleaning).

## 1.0 Importing the data

We load the users table into a pandas DataFrame. `df.head()` shows the first few rows so we can eyeball what we're working with.

In [2]:
import pandas as pd

data_path = "../data/raw_data/users.csv"
df = pd.read_csv(data_path)
df.head()

,user_id,signup_date,plan_tier,company_size,region,industry,acquisition_channel,is_enterprise,churned_30d,churned_90d,downgraded,expansion_event
0,f94d1824-8742-4000-8b6d-39d70958490b,2024-05-13,free,11-50,EU,software,seo,False,0,0,0,1
1,238bf0af-1f71-45e4-a47d-dcb5db33f71b,2025-04-11,standard,1-10,NaN,education,seo,False,0,0,0,0
2,ccf8fc06-3c86-433c-8867-9cba0fda337b,2024-10-28,free,1-10,APAC,transport,partner,False,0,0,0,1
3,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,2024-05-17,standard,200+,APAC,software,partner,False,0,0,0,1
4,9304dcbe-682d-41fa-8bfd-861559f9f58b,2024-04-12,free,1-10,NaN,software,ads,False,0,1,0,1

## 1.1 Handling duplicate values

Duplicate rows quietly **skew** the data - the model sees the same customer twice and over-weights that pattern.

Duplicates aren't always *exact* copies. If a user accidentally submitted the same form twice, the timestamp might differ while every other field is identical. So beyond exact matches, it's worth checking for repeats on the columns that *should* be unique - like `user_id`.

In [3]:
df.duplicated().sum()

np.int64(0)

There are no exact duplicate rows in this dataset.

It's still worth a closer look using a bit of context about the data. For example, we can check whether a single `user_id` appears more than once - which would tell us a user was recorded twice with only (say) the date differing.

In [4]:
df1 = df.drop_duplicates(subset=["user_id"], keep="first")
print(len(df), len(df1))

100000 100000

Luckily, no duplicate users either - every `user_id` is unique.

## 1.2 Inconsistent formatting

To a human, "Sydney" and "sydney" mean the same city. To a machine-learning model they are **two completely different categories** - inconsistent capitalisation, whitespace, or date formats all fragment your data and confuse the model.

`df.info()` shows the data types and non-null counts; `value_counts()` lists every distinct value in a column, which instantly surfaces "sydney vs Sydney" style problems.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   user_id              100000 non-null  str
 1   signup_date          100000 non-null  str
 2   plan_tier            100000 non-null  str
 3   company_size         100000 non-null  str
 4   region               61776 non-null   str
 5   industry             100000 non-null  str
 6   acquisition_channel  100000 non-null  str
 7   is_enterprise        100000 non-null  bool
 8   churned_30d          100000 non-null  int64
 9   churned_90d          100000 non-null  int64
 10  downgraded           100000 non-null  int64
 11  expansion_event      100000 non-null  int64
dtypes: bool(1), int64(4), str(7)
memory usage: 8.5 MB

In [7]:
print(df["region"].value_counts())

region
APAC     27810
EU       25960
LATAM     8006
Name: count, dtype: int64

## 1.3 Identifying missing values

Real data has holes. `isnull()` flags missing cells, and `isnull().sum()` counts them per column so we can see which features are affected.

In [8]:
df.isnull()

,user_id,signup_date,plan_tier,company_size,region,industry,acquisition_channel,is_enterprise,churned_30d,churned_90d,downgraded,expansion_event
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,True,False,False,False,False,False,False,False
99996,False,False,False,False,True,False,False,False,False,False,False,False
99997,False,False,False,False,True,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

user_id                    0
signup_date                0
plan_tier                  0
company_size               0
region                 38224
industry                   0
acquisition_channel        0
is_enterprise              0
churned_30d                0
churned_90d                0
downgraded                 0
expansion_event            0
dtype: int64

The **`region`** feature has a few missing values. Let's look at the affected rows.

In [10]:
df[df["region"].isnull()].head(5)

,user_id,signup_date,plan_tier,company_size,region,industry,acquisition_channel,is_enterprise,churned_30d,churned_90d,downgraded,expansion_event
1,238bf0af-1f71-45e4-a47d-dcb5db33f71b,2025-04-11,standard,1-10,NaN,education,seo,False,0,0,0,0
4,9304dcbe-682d-41fa-8bfd-861559f9f58b,2024-04-12,free,1-10,NaN,software,ads,False,0,1,0,1
7,3ea81032-dd9b-4ce2-bdf4-6a99c01fcff0,2025-05-12,free,200+,NaN,energy,outbound,False,0,0,0,0
10,904f47f7-6f21-41b9-b031-86dd264376b3,2025-05-04,free,51-200,NaN,transport,partner,False,0,0,0,0
11,c245c942-db9b-4a58-8722-7f52320ec347,2024-04-28,free,11-50,NaN,education,partner,False,0,1,0,1

**Option A - drop the rows.** As a rule of thumb, if only a few rows have a missing value, the simplest fix is to drop them with `dropna()`.

In [11]:
df1 = df.dropna().reset_index(drop=True)
df1.isnull().sum()

user_id                0
signup_date            0
plan_tier              0
company_size           0
region                 0
industry               0
acquisition_channel    0
is_enterprise          0
churned_30d            0
churned_90d            0
downgraded             0
expansion_event        0
dtype: int64

The trade-off: dropping a row throws away every *other* value in it too. That's fine for a handful of rows, but wasteful if many rows each have a single gap.

In [12]:
print(f"Data points before dropping: {len(df)} \nData points after dropping: {len(df1)}")

Data points before dropping: 100000
Data points after dropping: 61776

**Option B - impute (estimate) the missing value.** When the data matters or gaps are common, we fill them in with a sensible guess instead of dropping.

- **Numerical data** → use the column **mean** or **median** - simple and fast, though slightly less accurate.
- **Categorical data** → use the **most frequent** category (the mode), or a placeholder like `"unknown"`.
- **Advanced methods** - iterative, KNN, or ML-based imputation actually *predict* the missing value from the other columns. More accurate, but significantly more computationally expensive.

Below we impute `region` (categorical) using the **mode**.

> ⚠️ **Split before you impute!** Learn the "most frequent region" from the **training data only**, then apply it to both train and test. Computing it over the whole dataset leaks test information into training and makes your evaluation dishonestly optimistic - this is **data leakage**.

In [ ]:
###Here we'll impute using the mode
from sklearn.impute import SimpleImputer                ## For filling missing values
from sklearn.model_selection import train_test_split    ## For creating training/testing sets
import numpy as np                                      ## Handling NaN values

imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
###Make sure you split your data before imputing! 
# Otherwise you leak information from test to train, making your evaluation overly optimistic
X = df.drop(["churned_30d", "churned_90d"], axis=1)

###We'll only account for one target variable for now
y = df["churned_30d"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
###It's a good idea to stratify on our target variable y, as it is more likely that there are a lot more retaining customers then churning customers. 
###We can also easily check this:
print(len(df[df["churned_30d"]==0]), len(df[df["churned_30d"]==1]))

###We can now impute our data
###Make sure we fit ONLY on our training data, and then transform both our training and test set.
X_train[["region_imputed"]] = imputer.fit_transform(X_train[["region"]])        
X_test[["region_imputed"]] = imputer.transform(X_test[["region"]])

87039 12961

In [ ]:
X_train.head()

We can check the imputation worked as expected.

In [ ]:
print(len(X_train[X_train["region_imputed"]==0]))

With the clean `region_imputed` column in place, we can drop the original `region` feature.

In [ ]:
X_train = X_train.drop(["region"], axis=1)
X_test = X_test.drop(["region"], axis=1)

## Saving the cleaned data

Cleaning is done. We save the processed train/test sets to `data/processed_data/` so the EDA and modelling notebooks can load them directly instead of re-cleaning from scratch.

In [ ]:
processed_path = "../data/processed_data"

X_train.to_csv(f"{processed_path}/X_train.csv", index=False)
X_test.to_csv(f"{processed_path}/X_test.csv", index=False)
y_train.to_csv(f"{processed_path}/y_train.csv", index=False)
y_test.to_csv(f"{processed_path}/y_test.csv", index=False)